### ISSUE TITLE
Support parsing gjs and gts in glimmerx environment

### ISSUE THREAD

**Issue by gabrielcsapo** [typed-ember/glint#535] opened 2023-02-22 16:37 UTC
When trying to run glint on a glimmerx project it does not parse gjs or gts files.

> glimmerx config
<img width="438" alt="Screenshot 2023-02-22 at 8 35 46 AM" src="https://user-images.githubusercontent.com/1854811/220694846-dd9fddc4-cc60-4e6a-8348-f2d8c608cac0.png">

> ember-template-imports
<img width="378" alt="Screenshot 2023-02-22 at 8 35 59 AM" src="https://user-images.githubusercontent.com/1854811/220694925-ae18fb3d-2053-4136-bdca-ef63558ddec3.png">

When parsing files setting glimmerx `isAnalyzableFile` comes back as false for any gjs or gts files.

**Comment by chriskrycho** [comment] 2023-03-14 00:28
*Technically* not a bug, because historically that was an unsupported configuration of GlimmerX. However, if/as we change that (and we should! We should 100% align them!) this should definitely update to support it. I'm marking this as an enhancement accordingly. Thanks for filing it!

**Comment by NullVoxPopuli** [comment] 2024-01-22 18:56
Related: https://github.com/typed-ember/glint/issues/678 :see_no_evil:

**Comment by NullVoxPopuli** [comment] 2024-03-28 20:31
We've dropped support for GlimmerX in https://github.com/typed-ember/glint/pull/716, so the next major of Glint will not have GlimmerX support.

See also this general tooling plan with the language servers: https://github.com/emberjs/rfcs/pull/1014

**Closed by NullVoxPopuli** 2024-03-28 20:31 UTC
Labels: enhancement
