### ISSUE TITLE
Turning off TS Language Server turns off too much comfort

### ISSUE THREAD

**Issue by gossi** [typed-ember/glint#550] opened 2023-03-30 12:58 UTC
I'm giving a testdrive to a glint project and I'm quite happy with how far glint is.

But when asked to turn off TS language server, that sounds like something wrong in the first place. Also I know glint language server is taking over, I realized a lot of comfort is gone, that I'm used to. Too often this is even hard to tell which tool actually provides a particular feature and I learned many of them come from eslint. As eslint support is coming (my project is from the times before) all is good on this front.

I was figuring out whether switching to glint is a productive enhancement or an experimental playground. For now it is still the latter and this is also expected, but I was wondering what does it take to become the super-charged productive environment.

From what I _think_ a lot of TS language server features are not there (turned off?). The feature I use the most is auto-completion for import statements, this does not work and I need to figure out all the import paths manually. As well as source actions around imports (remove unused, sort and organize imports, etc).

Is there a known list of features that are missing? Is there a list of feautres/roadmap? Anything that hints when turning into glint LS is a replacement?

**Comment by dfreeman** [comment] 2023-04-14 11:43
This is a dupe of #130. Any tracking of missing language server features is happening there.

**Closed by dfreeman** 2023-04-14 11:43 UTC
