### ISSUE TITLE
When disabling the built in VS-Code TypeScript Language Features, CMD + hover stops showing type preview

### ISSUE THREAD

**Issue by jsturgis** [typed-ember/glint#414] opened 2022-09-22 23:48 UTC
## Issue
When disabling the built-in VSCode TypeScript and JavaScript Language Features extension, CMD + hover over types stops showing a preview of the type.

## TS
![ezgif com-gif-maker](https://user-images.githubusercontent.com/619673/191870073-13afa474-14bc-414b-a5cc-2059e9e81857.gif)

## Glint
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/619673/191870072-98c0c29d-c172-40c8-b101-65ff33adb6cb.gif)

**Comment by chriskrycho** [comment] 2022-09-23 00:36
Thanks for the report! This is a duplicate of #130 (and related to #121), so I'm going to close it as a duplicate, but the extra report is appreciated! Most of those pieces are just a case of needing to wire up a couple more parts of the TS server API. As @dfreeman noted on #130, we’re happy to provide guidance there if you have any appetite to contribute!

**Closed by chriskrycho** 2022-09-23 00:36 UTC
