### ISSUE TITLE
Intellisense sometimes points to comments instead of matching function

### ISSUE THREAD

**Issue by wagenet** [typed-ember/glint#129] opened 2021-04-01 19:05 UTC
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/9835/113341806-7a79d100-92e2-11eb-86aa-5b051415acc4.png">

As you can see, it finds the right entry, but also finds something in a comment.

**Comment by wagenet** [comment] 2021-04-01 21:04
It's possible this is from another extension, but I can't figure out what it would be.

**Comment by wagenet** [comment] 2021-04-01 21:09
Might be UELS?

**Comment by dfreeman** [comment] 2021-04-02 10:40
This isn't behavior I've run into, and it's hard for me to imagine how it could be happening since it would involve TypeScript thinking comment text was a valid definition source, but I could definitely be missing something!

If you can provide code that reproduces this I'm happy to take a look. Or if you can check whether it persists with UELS disabled, that's valuable information too.

**Comment by dfreeman** [comment] 2021-04-20 17:25
We chatted out of band about this. Since it's not clear whether this is coming from Glint, I'm going to close it out for now, but if you (or anyone else) are ever able to reproduce I'm happy to reopen and take a look!

**Closed by dfreeman** 2021-04-20 17:25 UTC
